### ISSUE TITLE
Not working after upgrade to 2023.3

### ISSUE THREAD

**Issue by Kevvyg1** [briis/hass-weatherflow#61]
Hi, is it just me that has this issue, i see no other reports.  I roll back to 2023.2 and no issue

Logger: homeassistant.config_entries
Source: custom_components/weatherflow/__init__.py:72
Integration: WeatherFlow Weather ([documentation](https://github.com/briis/hass-weatherflow), [issues](https://github.com/briis/hass-weatherflow/issues))
First occurred: 4:27:04 PM (1 occurrences)
Last logged: 4:27:04 PM

Error setting up entry Green Farm for weatherflow
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/weatherflow/__init__.py", line 72, in async_setup_entry
    if hass.config.units.is_metric
AttributeError: 'UnitSystem' object has no attribute 'is_metric'

I am a basic user, apologies if a simple error on my part

**Comment by briis** [comment]
Duplicate of #59. If you update to the latest version this issue is fixed. HACS is not automatically checking for new versions so you need to trigger this manually by updating the Repository info. See more info in #59
