### ISSUE TITLE
Integration (posssibly) broke after Supervisor 2023.01.0

### ISSUE THREAD

**Issue by MattMake** [briis/hass-weatherflow#59]
After a supervisor upgrade from 2022.3.5 to 2023.01.0, the WeatherFlow integration broke.  I don't have any data on whether this is affecting anyone else, as I only have mine to check.  

Integrations tab shows 'Failed to set up'.  I did attempt to delete and re-add with the pertinent details but the integration still reverts to 'Failed to set up'.  Including an excerpt from the logs, hoping that will help narrow down the issue as widespread or just me.

2023-03-02 20:56:20.699 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Crystal Cove Drive for weatherflow
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 383, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/weatherflow/__init__.py", line 72, in async_setup_entry
    if hass.config.units.is_metric
AttributeError: 'UnitSystem' object has no attribute 'is_metric'

And:
2023-03-02 20:55:42.931 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration weatherflow which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2023-03-02 20:56:20.699 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Crystal Cove Drive for weatherflow
File "/config/custom_components/weatherflow/__init__.py", line 72, in async_setup_entry
2023-03-02 21:21:26.218 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Crystal Cove Drive for weatherflow
File "/config/custom_components/weatherflow/__init__.py", line 72, in async_setup_entry

Happy to pull additional data from logs, just need guidance on what is needed.

**Comment by jeremyhamm** [comment]
I have the same issue when updating Home Assistant Core to 2023.3.1.

**Comment by alexbromberek2020** [comment]
Me to after upgrading

**Comment by briis** [comment]
The fix for this was introduced in V1.0.8. Are you sure you are on the latest version?

**Comment by briis** [comment]
Duplicate of #47

**Comment by MattMake** [comment]
The fix was to go into HACS from the left rail menu list, and update the Weatherflow integration.  After this completed, the service runs fine now.

**Comment by briis** [comment]
I noticed that HACS has had some issues with not displaying updates. After the latest update of HACS, this seems to be fixed. So I can also recommend you do the same with the HACS integration.

**Comment by MattMake** [comment]
Fair point, I should mention this as well.  The version of HACS didn't show an upgrade option, so I had to perform one from the terminal:

 wget -O - https://get.hacs.xyz | bash -

HACS was upgraded after running this command, and like @briis says, this latest version fixed the upgrade capabilties.
